<?php $testimonial=$this->getTestimonial(); ?>
<div class="about_section" style="margin-left: -10px; padding-bottom: 2px;">
	<h1><?php echo $this->__('Customer Testimonials');?></h1>
</div>
<div id="layout">
<?php if ($testimonial->getSize()): ?>
  <div class="testimonials-section">
    <?php $i==0; foreach ($testimonial as $obj):?>
    <?php if($obj->getStatus()==1): ?>
    <div class="testimonial-row">
      <div class="image-section"> 
      	<?php if($obj->getAvatarName() != ''){ $avatarLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'magebuzz/avatar/'.$obj->getAvatarName(); ?>
        	<img src="<?php echo $avatarLink ?>" alt="test" height="113" width="132" />
        <?php } ?>
      </div>
      <div class="content-section">
        <div class="content-inner">
          <p><?php echo $obj->getTestimonial();?></p>
        </div>
        <div class="signature">
          <p><span class="green">- <?php echo $obj->getName(); ?></span> (<?php echo $obj->getAddress(); ?>) </p>
          <p>
          	<small class="orange">
          		<?php echo date('dS,M Y', Mage::getModel('core/date')->gmtTimestamp($obj->getCreatedTime())); ?>
          	</small>
          </p>
        </div>
      </div>
    </div>
    <?php endif; ?>
    <?php $i++; ?>
    <?php endforeach; ?>
    
    <div class="paging"> 
    	<?php echo $this->getPagerHtml(); ?>
    </div>

  </div>
  <?php else: ?>
	<p class="note-msg"><?php echo $this->__('There is no testimonial submitted.'); ?></p>
  <?php endif; ?>
</div>



































<?php /* ?>
<?php $testimonial=$this->getTestimonial(); ?>
<div class="customer-testimonials">
	<div class="page-title">
		<h1><?php echo $this->__('Customer Testimonials');?></h1>
        <?php if(Mage::getStoreConfig('testimonial/testimonial_options/allow_customers_write_testimonial') == 1):?>
		<div class="submit-testimonial">
				<button class="button" onclick="setLocation('<?php echo $this->getFormUrl(); ?>')">
					<span>
						<span>
							<?php echo $this->__('Submit Your Testimonial');?>					
						</span>
					</span>
				</button>
		</div>
        <?php endif ?>
    </div>
	<?php echo $this->getPagerHtml();?>
	<?php if ($testimonial->getSize()): ?>
		<?php $i==0; foreach ($testimonial as $obj):?>
			<?php if($obj->getStatus()==1): ?>
			<div class="customer-testimonials-content<?php if($i==0):?> first<?php endif;?><?php if($i==(count($testimonial)-1)):?> last<?php endif;?>" name="<?php echo $obj->getName(); ?>" id="<?php echo $obj->getName(); ?>">
				<div class="testimonial-content">
                    <div class="testimonial-content-avatar">
                        <?php
                            if($obj->getAvatarName() != ''){
                                $avatarLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .'magebuzz/avatar/'.$obj->getAvatarName();
                                ?><img src="<?php echo $avatarLink ?>" alt="test" height="120" width="120" /><?php
                            }
                        ?>
                    </div>
					<?php echo $obj->getTestimonial();?>
				</div>
				<div class="testimonial-source">
					<span class="testimonial-author"><?php echo $obj->getName(); ?></span>
					<span class="testimonial-date">
						<?php echo date('F d, Y', Mage::getModel('core/date')->gmtTimestamp($obj->getCreatedTime())); ?>
					</span>
				</div>
			</div>
			<?php endif ?>
			<?php $i++; ?>
		<?php endforeach;?>
		<?php echo $this->getPagerHtml(); ?>
	<?php else: ?>
		<p class="note-msg"><?php echo $this->__('There is no testimonial submitted.'); ?></p>
	<?php endif ?>
</div>
<?php */ ?>
