
<?php //echo $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('reports/product_viewed.phtml')->toHtml();?>

<?php //echo $this->getLayout()->createBlock('reports/product_viewed')->setTemplate('reports/product_viewed.phtml')->toHtml(); ?>
<!--
<ul id="scroller">
  <li>
	<h4>Wedding Saree - TST001</h4>
	<div class="image_area"><img src="<?php echo $this->getSkinUrl('images/pic11.jpg'); ?>" width="206" height="142" alt="" /></div>
	<div class="button_row">
	  <input type="submit" name="" value="" class="btn_buynow" />
	  <input type="submit" name="" value="" class="btn_shortlist" />
	</div>
  </li>
  <li>
	<h4>Wedding Saree - TST001</h4>
	<div class="image_area"><img src="<?php echo $this->getSkinUrl('images/pic11.jpg'); ?>" width="206" height="142" alt="" /></div>
	<div class="button_row">
	  <input type="submit" name="" value="" class="btn_buynow" />
	  <input type="submit" name="" value="" class="btn_shortlist" />
	</div>
  </li>
  <li>
	<h4>Wedding Saree - TST001</h4>
	<div class="image_area"><img src="<?php echo $this->getSkinUrl('images/pic11.jpg'); ?>" width="206" height="142" alt="" /></div>
	<div class="button_row">
	  <input type="submit" name="" value="" class="btn_buynow" />
	  <input type="submit" name="" value="" class="btn_shortlist" />
	</div>
  </li>
  <li>
	<h4>Wedding Saree - TST001</h4>
	<div class="image_area"><img src="<?php echo $this->getSkinUrl('images/pic11.jpg'); ?>" width="206" height="142" alt="" /></div>
	<div class="button_row">
	  <input type="submit" name="" value="" class="btn_buynow" />
	  <input type="submit" name="" value="" class="btn_shortlist" />
	</div>
  </li>
  <li>
	<h4>Wedding Saree - TST001</h4>
	<div class="image_area"><img src="<?php echo $this->getSkinUrl('images/pic11.jpg'); ?>" width="206" height="142" alt="" /></div>
	<div class="button_row">
	  <input type="submit" name="" value="" class="btn_buynow" />
	  <input type="submit" name="" value="" class="btn_shortlist" />
	</div>
  </li>
</ul>-->